### ISSUE TITLE
Adding toggle

### ISSUE THREAD

**Issue by zapdos26** [sgtcmofo/NoSideTorch#2]
Adding a command toggle to allow the player to turn on/off this functionality. For example: when harvesting sand, this plugin  would increase the difficulty if using the torch method.

**Comment by sgtcmofo** [comment]
Definitely forgot about the sand. What if we added a check for the material it’s being placed on. If it’s sand, allow it.  All though you can still put down a ground torch when harvesting sand. 

I’ll go ahead and put the material check when I get out of the office today.

**Comment by sgtcmofo** [comment]
Per Sl1p's minecraft chat, he stated no side torch whether on sand or not.  so it should be good to go.
